language: c
sudo:     false

addons:
  apt:
    packages:
      - help2man
      - libgmp-dev
      - libdb-dev

install:
  - mkdir "gnu-cobol" && cd "gnu-cobol"
  - svn checkout svn://svn.code.sf.net/p/open-cobol/code/branches/gnu-cobol-2.0 .
  - ./configure && make
  - export PATH="${PATH}:${TRAVIS_BUILD_DIR}/gnu-cobol/cobc"

before_script:
  - cd ${TRAVIS_BUILD_DIR}
  - make

script: ./cobmind --database ./test-data/CobMind-ipv4-24.mmdb --ip 127.0.0.1
