language: c
sudo:     false

addons:
  apt:
    packages:
      - help2man
      - libgmp-dev
      - libdb-dev

install:
  - mkdir "cobol"
  - mkdir "cobol-src" && cd "cobol-src"
  - svn checkout svn://svn.code.sf.net/p/open-cobol/code/branches/gnu-cobol-2.0 .
  - ./configure --prefix="${TRAVIS_BUILD_DIR}/cobol" --exec-prefix="${TRAVIS_BUILD_DIR}/cobol"
  - make && make install
  - export PATH="${PATH}:${TRAVIS_BUILD_DIR}/cobol/bin"

before_script:
  - cd ${TRAVIS_BUILD_DIR}
  - CFLAGS="-I${TRAVIS_BUILD_DIR}/cobol/include" LDFLAGS="-L${TRAVIS_BUILD_DIR}/cobol/lib" CBLFLAGS="-conf=${TRAVIS_BUILD_DIR}/cobol/share/gnu-cobol/config/default.conf" make

script: ./cobmind --database ./test-data/CobMind-ipv4-24.mmdb --ip 127.0.0.1
